url: "hazelnb.github.io" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "/sms-save-viewer" # the subpath of your site, e.g. /blog
title: "Mario Sunshine Save Viwer" # the name of your site, e.g. ACME Corp.
